In [1]:
import pandas as pd
import numpy as np
import fasttext

In [11]:
data = np.random.randint(1, 30, size=(20, 10))
print(data)
data[:, 0] = 1
print(data)

[[16  1 16  5 23 25  1 13 23 18]
 [21 19 17  8 27  8 23 15  7 13]
 [ 1 17 26 23 23 29 18  9  7 19]
 [14 19  9 25 14  3  1 28  1  7]
 [ 5  1  4 23 20 27 11  5  5 14]
 [18 13 15 25 11 17 23 27  1 19]
 [23 19 18  9 12 14 29 29 13 16]
 [ 6  1 26 22 17 16  4  5 19 13]
 [ 2  6  6 10 16 12  3 11 14  9]
 [ 9  7 12 25 16  4 26  2 29 24]
 [17 16 15  5 14 23 28 17 21 23]
 [15 14 11 12 29 11 10 26 28 17]
 [ 5 18 28 24 27 17 10 12 28 19]
 [18 25 21 14 13 29  1 17 15 29]
 [21  9 28  8 12 19 17 24 28 21]
 [ 4 11  4 25 12 15 15 26  3 17]
 [ 3 25 11 12 28  7 24 24 28 24]
 [ 7 29  8 25 11  8 15  9  6 23]
 [11  2  9 13 13  7 13 11  6  2]
 [23  6 28 21  2 29  9 10 20  3]]
[[ 1  1 16  5 23 25  1 13 23 18]
 [ 1 19 17  8 27  8 23 15  7 13]
 [ 1 17 26 23 23 29 18  9  7 19]
 [ 1 19  9 25 14  3  1 28  1  7]
 [ 1  1  4 23 20 27 11  5  5 14]
 [ 1 13 15 25 11 17 23 27  1 19]
 [ 1 19 18  9 12 14 29 29 13 16]
 [ 1  1 26 22 17 16  4  5 19 13]
 [ 1  6  6 10 16 12  3 11 14  9]
 [ 1  7 12 25 16  4 26  2 29 24]
 [ 1 16 1

In [7]:
dataset = pd.read_csv('../data/data.csv')

In [4]:
def transform_text(text):
    return text.lower()

In [5]:
text = dataset['en'].apply(transform_text)

In [7]:
text.head()

0                                             into two
1    11 like a dog that returns to its vomit, the s...
2                                                 rush
3    4 so his father-in-law, the young woman’s fath...
4                                     trap for animals
Name: en, dtype: object

In [8]:
documents = text.tolist()
sentences = "\n".join(documents)

In [9]:
with open('engtext.txt', 'w', encoding='utf-8') as f:
    f.write(sentences)

In [10]:
model = fasttext.skipgram('engtext.txt', '../embeddings/eng-embeddings', dim=256)